### ISSUE TITLE
What's the reason of image_view and rqt_image_view are separately implemented

### ISSUE THREAD

**Issue by 130s** [ros-perception/image_pipeline#158]
Title says pretty much everything. I'm just wondering.

**Comment by vrabaud** [comment]
image_view is lightwright: it's only OpenCV. You choose a topic on the command line, view an image and save it. It uses a nodelet which actually creates problems on some platforms /OpenCV.
rqt_image_view is integrated in rqt which allows dynamic choosing of the topic, refresh rate, pause, full screen.
rqt_image_view should just be image_view with a better GUI. Now, as image_view historically uses nodelets, rqt_image_view did not use that nodelet and re-wrote the code (plus Qt does nto allow grayscale images to be displayed, so conversions are different).

That's why I started writing this common code. Then again, image_view needs to be re-written like rqt with only a stupid loop that displays imaging. No more nodelets ! (because the threading model of nodelets interferes with the threading model of OpenCV for GUIs). I just could never find the time for it .... If you feel like, please make a pull request, I know it is totally trivial ! More discussion at https://github.com/ros-perception/vision_opencv/pull/81
