### ISSUE TITLE
Release into ROS Lunar

### ISSUE THREAD

**Issue by 130s** [ros-perception/image_pipeline#271]
[Some packages](http://repositories.ros.org/status_page/blocked_releases_lunar.html?s=6&r=1) want this package to be available.
Thanks!

**Comment by mikaelarguedas** [comment]
@130s FYI: released in https://github.com/ros/rosdistro/pull/14581

@vrabaud This needs a new release including https://github.com/ros-perception/image_pipeline/commit/562332df73781c1e56ce9123542334cc1d91b143, without it all jobs on yakkety, zesty and stretch are failing. If you have any spare cycle in the next few days it will be great because thats one of the 3 packages preventing the release of ROS Lunar desktop_full

**Comment by 130s** [comment]
Thanks @mikaelarguedas

**Comment by mikaelarguedas** [comment]
I'm going to reopen this given that a new release is needed to be able to release ROS Lunar

**Comment by vrabaud** [comment]
And done !
