### ISSUE TITLE
registration of color on point clouds does not work

### ISSUE THREAD

**Issue by vrabaud** [ros-perception/image_pipeline#3]
See turtlebot/turtlebot#33

And there might be another issue in there with grayscale/color (second comment of @jihoonl)

**Comment by chadrockey** [comment]
Looks like yuv422 is being published on image_color instead of being converted to rgb8.

https://github.com/ros-perception/image_pipeline/blob/master/image_proc/src/nodelets/debayer.cpp#L132

sensor_msgs/image_encodings.h reports yuv422 as a color encoding, so image_proc is not reaching the YUV422 if/else block.
https://github.com/ros/common_msgs/blob/master/sensor_msgs/include/sensor_msgs/image_encodings.h#L107

**Comment by vrabaud** [comment]
fixed in 1.9.12
