### ISSUE TITLE
stereo_image_proc vs triclops SDK

### ISSUE THREAD

**Issue by aswinthomas** [ros-perception/image_pipeline#30]
Hi all,
I am very new to stereo vision and recently got the bumblebee xb3.

Does anyone know the difference in performance between 3D pointcloud generated by stereo_image_proc vs triclops SDK? I understand the techniques used are the same. Is it better, worse or same?

In addition to this, is there anyway I could use the stereo_image_proc for more than 2 lens?

Cheers
Aswin

**Comment by vrabaud** [comment]
I honestly have no idea on what their SDK is doing and for the performance comparison. You would probably have more answers on http://answers.ros.org/
For your second question, the stack only works with 2d and is not going to work with more cameras any time soon, mostly because there are no pieces of code in OpenCV doing that. But if you have code that does that, please, we'll definitely integrate it !
