### ISSUE TITLE
Question: Working with underwater images

### ISSUE THREAD

**Issue by ne-v0y** [ros-perception/image_pipeline#387]
Sorry to ask a question here, but I'm just curious if `image_proc` works with underwater images?

**Comment by SteveMacenski** [comment]
Hi,
There's no reason why image_proc or any algorithm _wouldnt_ work just because of where the images are taken from. With that said without knowing which items you're trying to use, I can't make a definitive statement. 

Cropping/decimating an image is cropping/decimating an image regardless of what the image is. Stereo is stereo as long as there are features.
