### ISSUE TITLE
Video tutorials private

### ISSUE THREAD

**Issue by javierBarandiaran** [ros-perception/image_pipeline#705]
The videos tutorials are private
http://wiki.ros.org/image_pipeline/Tutorials
Could you make them public please?

**Comment by JWhitleyWork** [comment]
Sorry but I have no idea where these videos are/were. The error I'm seeing in the preview is that the video can not be found, not that it's private so I would guess that they have been deleted.

**Comment by lucasw** [comment]
You could get in touch with the author of that change to the wiki that posted the videos (back in 2010):

http://wiki.ros.org/action/diff/image_pipeline/Tutorials?action=diff&rev1=12&rev2=13

The wayback machine says the first one was called "Part 1 of 3: Processing Camera Data", no sign of that anywhere else: https://web.archive.org/web/20170824232305/http://wiki.ros.org/image_pipeline/Tutorials

The full youtube pages like https://www.youtube.com/watch?v=iWfqQGUjgoo do indicate they are private. 
 Maybe they'd agree to have them unlisted rather than private, otherwise that wiki ought to be edited to remove them (I can do that if no one else).
