### ISSUE TITLE
ROS2 resize and rectify always subscribe to the raw image

### ISSUE THREAD

**Issue by clydemcqueen** [ros-perception/image_pipeline#706]
In ROS2 `RectifyNode::subscribeToCamera` calls `image_transport::create_camera_subscription`, which doesn't get the value of the image_transport parameter, so it always subscribes to the raw image on the base topic.

In ROS1 `RectifyNodelet::connectCb` calls `image_transport::subscribeCamera` and passes in a TransportHint. The TransportHint object will get the value of the image_transport parameter, allowing users to choose a different transport at runtime.

https://github.com/ros-perception/image_pipeline/blob/71d537a50bf4e7769af513f4a3d3df0d188cfa05/image_proc/src/nodelets/rectify.cpp#L108

Same goes for ResizeNode.

I'm not sure if the fix should land in image_transport or image_proc.

Thanks.

**Comment by mikeferguson** [comment]
Added to meta ticket for image_transport updates: https://github.com/ros-perception/image_pipeline/issues/854

**Comment by ndahn** [comment]
@mikeferguson Is this really resolved? I'm on Jazzy and while my RectifyNode seems to yield the topic as expected, my ResizeNode still keeps the subscription indefinitely.

**Comment by ndahn** [comment]
Ah, the issue is a bit more complex after all. I was trying to remap the camera_info topic that ResizeNode creates separate from the resized output topic. However, it seems this topic cannot be remapped and will always stick to the image topic. This resulted in a second publisher to my camera's camera_info. 

This issue seems to describe the root of the problem: https://github.com/ros-perception/image_common/issues/147. So nothing to be done on this repo.
