### ISSUE TITLE
cameracheck.py not responding

### ISSUE THREAD

**Issue by roaz1801** [ros-perception/image_pipeline#729]
Hello, I have calibrated a camera using camera_calibrator.py. After calibrating I have commited and used the http://wiki.ros.org/image_proc package to get the rectified image. I want to check how good the calibration is, but when running 
`python3 cameracheck.py --size 8x6 --square 0.25 image:=/cv_camera/image_rect_color camera:=/cv_camera`
the node is unresponsive, no output or errors.
Using Ros noetic on Ubuntu 20.04, and using the latest version of the package

**Comment by mikeferguson** [comment]
I think the issue here is that you need to remap "monocular/image_rect" rather than "image" - I suggest taking a look at what topics the cameracheck.py is actually subscribing to when running.

If you need further help, I would suggest posting to https://robotics.stackexchange.com - that is a more appropriate place for debugging/questions.
