### ISSUE TITLE
Porting Rolling Changes and New Releases

### ISSUE THREAD

**Issue by JWhitleyWork** [ros-perception/image_pipeline#759]
@clalancette - It's been over a year since the `ros2` and `rolling` branches diverged. It now looks like releases are being made on `rolling` even though both branches have mutually-exclusive commits. Is there a plan for merging the two? The initial intent of the `rolling` branch was to test features related to other repositories which had changes in `rolling` but this seems to have become a staging ground for a huge number of changes, some of which I suspect should have been put into `ros2` (existing releases) instead. Thoughts?

**Comment by clalancette** [comment]
In short, I'm not a maintainer here, so I don't know.

I'll point out that both https://github.com/ros2-gbp/image_pipeline-release/blob/master/tracks.yaml#L127-L152 and https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L1477-L1502 refer to the 'rolling' branch, so that is the canonical branch where releases should be made.  That also matches our new suggested setup for branches, to have a dedicated named 'rolling' branch.

That said, the older distributions are a mess.  Humble references the rolling branch (not entirely surprising, but perhaps wrong), while both Galactic and Foxy reference the 'ros2' branch.

My suggestion here is to:

1. Create a new 'foxy', and 'galactic' branch from the existing 'ros2' branch
2. Create a new 'humble' branch from the existing 'rolling' branch
3. Update the tracks.yaml and the distribution.yaml for all of them to point to the right name
4. Port the appropriate commits from 'ros2' over to 'rolling', so that 'rolling' has all of the latest code
5. Do releases into all of Rolling, Humble, Galactic, and Foxy

I think that should clear this all up and make it easier going forward.

**Comment by ijnek** [comment]
I'm guessing we're up to step 3 from the previous comment.
I've prepared step 4: https://github.com/ros-perception/image_pipeline/pull/761

It'll also be nice to delete the ``rolling-rebase`` branch, I don't know what that is but it seems stale.

**Comment by ijnek** [comment]
@JWhitleyWork With up to step 4 being completed, could you consider deleting the ``ros2`` branch to prevent further branch diversion?

**Comment by JWhitleyWork** [comment]
The `ros2` branch is now gone. Making releases for all currently-supported ROS2 branches (i.e. Rolling, Humble, and Foxy).

**Comment by JWhitleyWork** [comment]
New releases created for [foxy](https://github.com/ros/rosdistro/pull/35556) and [rolling](https://github.com/ros/rosdistro/pull/35557) (Humble got a release very recently and only has 1 minor change since then). I think we can now consider this RESOLVED. Please re-open if there are additional issues that I'm not aware of.

**Comment by ijnek** [comment]
Thanks @JWhitleyWork !
